on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nosborn/github-action-markdown-cli@58564a147ff6d7fae834bcc73eafc26eaf264391
        with:
          files: .
