on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nosborn/github-action-markdown-cli@3827e97df63fc9c7c6f2da377097e10cb350a22b
        with:
          files: .
