on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nosborn/github-action-markdown-cli@691419e4c8d647fc4b92eb9a05195f69a9351edd
        with:
          files: .
