name: Update contributors

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0

      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2.4.1
        name: Install pnpm

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies & update contributors
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_MEMBERS_TOKEN }}
        run: |
          pnpm install --frozen-lockfile
          pnpm run update-contributors
          pnpm run format

      - name: Commit files
        run: |
          git config --local user.email "gitbot@scrumplex.net"
          git config --local user.name "PrismAutomata"
          git add :/
          git commit -m "Update contributors" || true

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          base: "main"
          branch: "update-contributors"
          delete-branch: true
          title: "chore: update contributors"
          body: "Automated pull request to update contributors"

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3.0.0
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
